name: docker-beta
on:
  push:
    branches:
      - 'main'
env:
  APP_NAME: bepusdt-custom
  DOCKER_HUB_USER: uby777881
  DOCKER_HUB_REPO: uby777881/bepusdt-custom
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: 'main'
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_BETA_TOKEN }}
      - name: Generate App Version
        run: echo "APP_VERSION=$(git rev-parse HEAD | cut -c 1-6)" >> $GITHUB_ENV
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          build-args: |
            APP_NAME=${{ env.APP_NAME }}
            APP_VERSION=${{ env.APP_VERSION }}
          tags: |
            ${{ env.DOCKER_HUB_REPO }}:beta
            ${{ env.DOCKER_HUB_REPO }}:beta-${{ env.APP_VERSION }}